name: Publish to PyPI
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  publish:
    name: publish
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel

      - name: Build distribution
        run: |
          rm -rf dist
          python setup.py sdist bdist_wheel

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}