name: run unit tests
on:
    push:
        branches:
            - main
    pull_request:
    workflow_call:

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: python -m pip install -r requirements.txt

            - name: Run tests
              run: |
                python -m pytest ./tests